Added APIs for Point Generation
Capstone-537-565-609-668/flask_backend pull request #2
Opened 2023-11-06 12:51 UTC by Veeresh-R-G

Added two API routes for Point Generation
- `/generate_points_voronoi` : Uses Voronoi algorithm to generate Points
- `/generate_points_convexHull` : Uses Convex Hull algorithm to generate Points

2023-11-06 13:36 UTC, Nireekshadrai requested changes

2023-11-06 13:36 UTC, Nireekshadrai commented on generate_set.py
> +
```suggestion
dataset_descriptor, json_visualization_data = convert_for_visualize([
            polygon])
```

2023-11-08 15:44 UTC, Ankur-Datta-4 commented on app.py
> +    card = int(request.get_json()['card'])
Try to keep a limit on the card input as 10..
Ask the user to use MBR based stuff

2023-11-08 15:44 UTC, Ankur-Datta-4 commented on app.py
> +@app.route("/generate_points_convexHull/", methods=["POST"])
Remove caps from url

2023-11-08 15:55 UTC, merged